### ISSUE TITLE
 Фидбек по конкурсной работе от проверяющих

### ISSUE THREAD

**Issue by b1ng0o** [EIDiamond/invest-bot#1]
Привет! 
Хорошая работа!
Рекомендуем доработать:

- логирование сделав его более информативным
- работу без Телеграмм бота
- функциональные возможности

**Comment by EIDiamond** [comment]
Привет!
Большое спасибо за фидбек по работе. 
Отличный конкурс было очень интересно.

Стоит отметить, что отключение Телеграмм бота было в конкурсной версии 
![image](https://user-images.githubusercontent.com/105827519/174390428-951719b0-852b-492d-b90f-a3fe9bf7c1dc.png)

В остальном, буду дорабатывать.
