### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by Liddel2019** [EIDiamond/invest-bot#10]
MAX_LOTS_PER_ORDER
Что делает эта настройка?
я сначала думал что это кол во лотов за ордер ( а максимальное колличество рассчитывается исходя из баланса), но моя теория не подтвердилась. я выставил 1 вместо 3, и после сигнала 2й лот не докупился. можете реализовать логику работы при которой можно выбрать максимальное колличество лотов и колличество лотов покупаемых при сигнале. например, максимум лотов 5, а за раз 1 , поступает 3 сигнала long, и покупается по одному лоту 3 раза. это бы очень сильно улучшило работу различных стратегий ( из за того что был бы меньше минус, появилось бы возможность усреднения, и тд)

**Comment by Liddel2019** [comment]
Так же если например если есть несколько акций и поступают сигналы для разных акций то они не пропускаются ( из за того что в принципе больше 1 сигнала не может использоваться )

**Comment by EIDiamond** [comment]
MAX_LOTS_PER_ORDER - это максимальное колличество лотов на открытие позиции. При открытии позиции происходит расчет колличества лотов доступных для покупки исходя из свободных средств. Если колличество лотов (которые можно купить на доступные средства) большое MAX_LOTS_PER_ORDER, то будет куплено MAX_LOTS_PER_ORDER, если меньше, то расчитанное колличество. Т.е. это ограничение сверху. Можно рассматривать его как "не более чем".

**Comment by EIDiamond** [comment]
> Так же если например если есть несколько акций и поступают сигналы для разных акций то они не пропускаются ( из за того что в принципе больше 1 сигнала не может использоваться )

Не совсем понял. Каждая акция отдельно обрабатывается. Например: если есть открытая позиция по SBER, и приходит сигнал на покупку GAZP, то GAZP будет куплен. Сигналы, свечи и стартегии не пересекаются между собой. Если это не так приложите логи возмонжо тут баг.

**Comment by EIDiamond** [comment]
> можете реализовать логику работы при которой можно выбрать максимальное колличество лотов и колличество лотов покупаемых при сигнале. например, максимум лотов 5, а за раз 1 , поступает 3 сигнала long, и покупается по одному лоту 3 раза. это бы очень сильно улучшило работу различных стратегий ( из за того что был бы меньше минус, появилось бы возможность усреднения, и тд)

Да, как усреднение я не заложил :). 

Я правильно понимаю, что : 
Сейчас: Если открыта позиция и приходит любой сигнал, то он пропускается
Вы предлагаете: Если открыта позиция и приходит сигнал в ту же сторону, то докупать. 

В целом, тут уместно и изменение которые обсуждали в другом issue на противоположны сигнал. 
Вам это еще нужно. Просто issue закрыли и не понятно.

**Comment by Liddel2019** [comment]
Я точно помню как пол года назад я тестировал стратегию и когда было было больше 1 инструмента, при наличии заявки на любой инструмент пропускались сигналы с другим инструментом. Позже попробую отправить логи если получится повторить ситуацию. Про возможность покупаться я, считаю хорошо я функция

**Comment by Liddel2019** [comment]
По поводу того почему закрыл issue, я понял что чат gpt не справляется с задачей даже если , ему давать четкую задачу и делать обзор ошибок в коде.

**Comment by EIDiamond** [comment]
Чат GPT еще рано такое давать :). 

Хорошо, я попробую помочь как будет время. Issue не закрывайте, а то я забуду.

**Comment by EIDiamond** [comment]
Добавил возможность закрывать позицию, по сигналу из стратегии. То что обсуждали в другом issue. 

Стратегия может сгенерить сигнал из метода def analyze_candles. 
Добавлен новый тип сигнала: SignalType.CLOSE = 2 
Если стратегия решает закрыть позицию сама (не по take \ stop уровням), то она должна вернуть сигнал с таким типом. Дальше если есть открытая позиция, то она будет закрыта. 

Остальные предложения в следующий раз уже.

**Comment by Liddel2019** [comment]
Спасибо!
