### ISSUE TITLE
Контакт для связи 

### ISSUE THREAD

**Issue by b1ng0o** [EIDiamond/invest-bot#2]
Добрый день!

Меня зовут Юрий, из Тиньков public invest API.

Мы сейчас пишем ряд статей на хабр про торговых роботов, и в статье про пайтон, хотели бы указать Вас как автора одного из наиболее качественных роботов, и ваш репозиторий как пример торгового робота.  Как вы на это смотрите?
Не могли бы вы оставить  email или телеграмм для связи?

**Comment by EIDiamond** [comment]
Доброй ночи, Юрий. 

Поработав более плотно с Tinkoff Invest API и биржевой торговлей в целом, я осознаю что мой торговый робот, является лишь небольшим примером, написанным в сжатые сроки и не более того. Мой набор переработок (TODO) уже перевалил за 3 страницы мелким шрифтом, не хватает только времени.  

Большое спасибо, за высокую оценку проекта, но я не считаю робота качественным и тем более готовым к какому-то реальному использованию. Чтобы не вводить в заблуждение читателей хабр, я прошу не упоминать проект в статье.

**Comment by b1ng0o** [comment]
Добрый день! Хорошо, спасибо за обратную связь.
