### ISSUE TITLE
Margin trading

### ISSUE THREAD

**Issue by Liddel2019** [EIDiamond/invest-bot#3]
the bot does not trade with leverage, if for example the bot trades with 5x leverage, 1x, then why set up a minimum liquid portfolio?  I set the maximum number of lots with the condition of margin trading, but he buys less, maybe
![Screenshot_2023-09-27-12-16-11-774_ru tinkoff investing](https://github.com/EIDiamond/invest-bot/assets/54450240/6cb86d86-7722-4801-a673-5c9888223000)
![Screenshot_2023-09-27-12-16-46-632_com google chromeremotedesktop](https://github.com/EIDiamond/invest-bot/assets/54450240/440da56b-189c-4f29-92f0-1b45f08ea521)
![Screenshot_2023-09-27-12-17-20-549_ru tinkoff investing](https://github.com/EIDiamond/invest-bot/assets/54450240/c828606c-da82-4a7b-b9d0-f3ecb7f9b7cd)
 I’m doing something wrong?

**Comment by EIDiamond** [comment]
Привет, это изначально задуманное поведение:
1) При выборе колличества лотов на покупку происходит расчет свободных средств и колличества лотов, которые можно купить на них. 
2) Далее происходит сравнение вычисленного колличества лотов и значения MAX_LOTS_PER_ORDER. Выбирается меньшее значение из двух, т.е. настройка MAX_LOTS_PER_ORDER - это верхняя граница колличества лотов. Именно граница, а не конкретное указание.   

Расчет свободных средств - это именно свободных денег. Например: на счету 10 000 рублей. Были произведены две сделки: лонг позиция по акции X 1 лот на 1 000 рублей и шорт позиция по акции Y 1 лот на 2 000 рублей. Таким образом, расчет свободных средств будет равен 10 000 - 1 000 - 2 000 = 7 000 рублей. 
ПС. В такой ситуации Тинькоф Инвестиции нарисует мифические 11 000 рублей, но было решено не использовать их подход к расчету средств. 

Добавлю лично от себя: Я настойчиво НЕ рекомендую использовать маржинальную торговлю. Пару лет назад я очень сильно обжегся с этой темой. Поэтому бот перенял от меня не любовь к маржинальной торговле.

**Comment by Liddel2019** [comment]
Хорошо спасибо
