### ISSUE TITLE
 market_data_stream_service - ERROR

### ISSUE THREAD

**Issue by Liddel2019** [EIDiamond/invest-bot#4]
Во время работы бота происходят ошибки. Что сделать что бы их не было?
Windows 10 Pro 22H2 19045.3448
Python 3.11.5
tinkoff-investments 0.2.0b60
aiogram  3.0.0
Интернет подключен через WiFi адаптер

Errors occur while the bot is running.  What can be done to prevent them from happening?
 Windows 10 Pro 22H2 19045.3448
 Python 3.11.5
 tinkoff-investments 0.2.0b60
 aiogram 3.0.0
 Internet connected via WiFi adapter

https://www.speedtest.net/result/15325988382.png

**Comment by EIDiamond** [comment]
Привет, я отредактировал Ваш комментарий и удалил ссылку на лог. В логе был токен телеграмм бота и чат id. Рекомендую удалить и создать телеграм бота заново.

**Comment by EIDiamond** [comment]
Касательно вопроса. 
К сожелению, такие ошибки никак не убрать и это не зависит от подключения. Я тоже наблюдаю такого рода ошибки каждый день. Это на стороне Tinkoff API:

https://github.com/Tinkoff/invest-python/issues/160
https://github.com/Tinkoff/invest-python/issues/210

В последнем issue руководитель команды API в целом дает ответ:
https://github.com/Tinkoff/invest-python/issues/210#issuecomment-1482780561

В последней версии бота сделан reconnect по рекомендации, большего на строне бота уже не сделать.

**Comment by Liddel2019** [comment]
Спасибо за ответ
