### ISSUE TITLE
Нужна помощь со стратегией

### ISSUE THREAD

**Issue by Liddel2019** [EIDiamond/invest-bot#5]
Здраствуйте, я к сожалению еще не знаю python на достаточно хорошем уровне и поэтому прошу помощи. У меня есть стратегия из другого бота - [IntervalStrategy](https://github.com/qwertyo1/tinkoff-trading-bot/blob/develop/app/strategies/interval/IntervalStrategy.py) (https://github.com/qwertyo1/tinkoff-trading-bot). Если кому не сложно, можете помочь с тем чтобы изменить код так что бы это заработало. Могу дать на чай рублей 300. Заранее спасибо за ответ. Мой тг @liddel_off

**Comment by EIDiamond** [comment]
Здравствуйте, опишите пожалуйста подробнее вашу идею. Что хотите сделать, какие изменения внести и что получить по итогу?

**Comment by Liddel2019** [comment]
Я хочу что бы кто-нибудь мне помог с переносом interval стратегии из одного бота в другого. Суть стратегии, бот анализирует предыдущие свечи за выбранный период и стоит коридор, при достижении минимума акция покупается, максимума продается, коридор автоматически обновляется что позволяет боту работать автономно ( коридор не задаётся вручную) . Я хотел попробовать перенести сюда эту стратегию но моих навыков не хватает(

**Comment by Liddel2019** [comment]
Вот файлы со стратегией из другого бота. Они должны быть в формате .py но на гитхабе пишет что нельзя такие отправлять 
[IntervalStrategy.log](https://github.com/EIDiamond/invest-bot/files/12832718/IntervalStrategy.log)
[models.log](https://github.com/EIDiamond/invest-bot/files/12832721/models.log)

**Comment by EIDiamond** [comment]
Если подвести итого: Вы хотите реализовать стратегию по ссылке выше в нашем боте? Я правильно вас понял?

**Comment by Liddel2019** [comment]
Да,

**Comment by EIDiamond** [comment]
Мы посмотрели стратегию и пришли к выводу, что это стратегия-пример, чтобы другие могли добавить свою стратегию сами. 

Как собственно стратегия и в нашем боте. Стратегия есть и одна добалена в бот, но служит лишь примером, так как реальная доходность у нее отрицательная. Что в целом логично, так как никто не будет доходную стратегию выкладывать в публичный репозитарий. 

Если вы хотите серьезно заниматься алгоритмической торговлей, мы рекомендуем вам, изучить языки программирования и разработать свою стратегию.

**Comment by Liddel2019** [comment]
Спасибо
