### ISSUE TITLE
Покупка и продажа не по take_profit а по сигналу

### ISSUE THREAD

**Issue by Liddel2019** [EIDiamond/invest-bot#8]
Можно ли реализовать в стратегии покупку и продажу без take_profit и stoploss?

**Comment by EIDiamond** [comment]
Как будет закрываться позиция? Подразумевается, что стратегия с ордерами не работает, а только дает сигналы. В целом это можно сделать, например так. Добавить сигнал типа "закрытие позиции". Стратегия когда решит закрыть позицию выдаст сигнал на закрытие, так же как и long и short сигналы. В целом, это будет юзабельно даже для других стратегий. 
Можно доработать бота до такого варианта. 

Что касается take_profit и stoploss:
1) Вообще рекомендую в любом случае использовать stoploss
2) Их можно уже отключить. Надо чтобы стратегия, когда создает сигнал просто выставляла **неадекватные** значения для take_profit и stoploss. Например SBER и Long. take_profit  = 100 000 000 и stoploss = - 1 000 000. Тогда они никогда не наступят.

**Comment by Liddel2019** [comment]
Если не сложно можете написать пример функции в которой есть возможность досрочно закрыть позицию

**Comment by Liddel2019** [comment]
Да
