### ISSUE TITLE
Будет ли это работать?

### ISSUE THREAD

**Issue by Liddel2019** [EIDiamond/invest-bot#9]
Я добавил досрочное закрытие позиции и открытие новой если появляется противоположный сигнал и профит больше 0.
[trader.txt](https://github.com/EIDiamond/invest-bot/files/14624674/trader.txt)

**Comment by Liddel2019** [comment]
Изменения вносил только в __trading

**Comment by EIDiamond** [comment]
1) Строка 172 и 173. Это условие отсеет сигнал и новый код не вызовется. 
2) Строка 221. У TradeOrder нет свойства open_price
3) Само расположение надо изменить. По else в условии (строка 176) идет открытие позиции если никаких позиций нет. Я бы пытался разместить новый код там где 173 строка шас. Т.е. 173 строка отрабатывает, если есть уже открытая позиция и можно с этим дальше уже работать

**Comment by Liddel2019** [comment]
Спасибо!

**Comment by Liddel2019** [comment]
Если не сложно, можете посмотреть? ( большую часть кода пишу не я, тк нет достаточных умений, по этому к сожалению отвлекаю вас что бы вы смогли дать оценку работоспособности кода. Извиняюсь за ваше потраченное время)
[trader_new.txt](https://github.com/EIDiamond/invest-bot/files/14625558/trader_new.txt)
[trader_new2.txt](https://github.com/EIDiamond/invest-bot/files/14625559/trader_new2.txt)

**Comment by EIDiamond** [comment]
Честно оба варианта выглядят не рабочими. 
[trader_new.txt](https://github.com/EIDiamond/invest-bot/files/14625558/trader_new.txt):
1. Строка 174 - continue тут означает переход к следующей свече, по сути ничего не изменилось, новый код не исполниться если есть открытая позиция. 
2. Профит расчитывается не верно. По сути это разница между открытием и закрытием текушей свечи. Это явно не профит от позиции. 
3. Строка 236 тут не стоит ставить else условие. Вообще по else для этого if Не надо ничего делать. Так как if на условие, что сменилась свеча (прошла минута и свеча стали последней в этой минуте и ее можно начинать анализировать) иначе свеча как бы еще не итоговая для данной минуты + проверка на то что время для торговли истекло. 

[trader_new2.txt](https://github.com/EIDiamond/invest-bot/files/14625559/trader_new2.txt)
1. тоже самое что и выше
2. тоже самое что и выше
3. Новый код расположен не там так как нету сигнала еще + свеча как я писал еще не окончательная. 

Я писал выше что строка 173 в не измененном коде, лучшее место в котором лучше расположить новый код. Тут и свеча закрыт и есть новый сигнла и уже открыта старая позиция. Все готова для вашей идеи. 
Ну и надо придумать как расчитать правильно профит.
